USE Bank

UPDATE Employees
SET ManagerID =
CASE
	WHEN EmployeeID IN (11, 21) THEN 1
	WHEN EmployeeId BETWEEN 2 AND 10 THEN 1
	WHEN EmployeeId BETWEEN 12 AND 20 THEN 11
	WHEN EmployeeId BETWEEN 22 AND 30 THEN 21
END